version: "3"
services:
  flood:
    hostname: flood
    image: jesec/flood
    user: 1003:1003
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 0.0.0.0:3001:3001

  rtorrent:
    hostname: rtorrent
    image: jesec/rtorrent
    user: 1003:1003
    restart: unless-stopped
    command: -o network.port_range.set=55494-55494,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 0.0.0.0:55494:55494
